Sprint Beschreibungen
HSLU-BaumannWicki/BDA_FS19-Dokumentation pull request #13
Opened 2019-04-23 11:08 UTC by KilnOfTheSecondFlame

Add a detailed description of the work done, add sprint goals and the challenges encountered.

Please advise if the structure like that is to your liking, or if you want sprint goals more visible as a separate header/table

2019-04-25 16:48 UTC, CryDeb requested changes
Irgendwie gefällt mir die Inhaltliche struktur der Sprints noch nicht -> kurz besprechen?

2019-04-25 16:48 UTC, CryDeb commented on include/Projektmanagementplan.tex
> +Der erste Sprint begann wie das ganze Projekt mit dem Kickoff-Meeting. Als Sprintziel war die Initialisierung definiert worden. Im Vorfeld erstellte Herr Baumann einen Grobplan, eine erste Risikoanal
Das Team bereitete sich auf *das* Meeting vor, indem es sich intensiv mit der Aufgabenstellung auseinandersetzte und bereits technische Überlegungen anstellte. Ungewissheiten wurden dabei gleich als fragen für den Kunden erarbeitet zudem wurde ein grober Zeitplan erarbeiteten. 

Hemmer da kei Problem gha?
So chlises Sprintfazit weri allefals no cool ;)

2019-04-25 16:48 UTC, CryDeb commented on include/Projektmanagementplan.tex
> +Der erste Sprint begann wie das ganze Projekt mit dem Kickoff-Meeting. Als Sprintziel war die Initialisierung definiert worden. Im Vorfeld erstellte Herr Baumann einen Grobplan, eine erste Risikoanal
Achtung ein Ziel ist SMART -> diese Ziele (gilt auch unten sind nicht smart)
(allenfals schnell zusammensitzten und diese erarbeiten?)

2019-04-25 16:48 UTC, CryDeb commented on include/Projektmanagementplan.tex
> +Im zweiten Sprint wurden die Erkenntnisse aus der Recherchephase umgesetzt. Daraus leitete sich das Sprintziel der Konzepte und Meilensteinsitzung ab. Im Speziellen erhielt Herr Baumann den Auftrag e
Hier gutes Ziel: Am ende dieses Sprintes sollen 2 Unterschiedlich definierte Konzepte genauer beschrieben sein.

2019-04-25 16:48 UTC, CryDeb commented on include/Projektmanagementplan.tex
> +Im zweiten Sprint wurden die Erkenntnisse aus der Recherchephase umgesetzt. Daraus leitete sich das Sprintziel der Konzepte und Meilensteinsitzung ab. Im Speziellen erhielt Herr Baumann den Auftrag e
Fazit etwas mehr?
Was verlief gut weshalb verlief es gut?

2019-04-25 16:48 UTC, CryDeb commented on include/Projektmanagementplan.tex
> +Aus der Meilensteinsitzung wurde klar, dass die Kosten für die ermittelten Geräte für Testzwecke und Prototypisierung zu hoch sind, und die nötigen Geldmittel weder vom Kunden noch vonseiten der Hoch
Herausforderung:
Absage aller anfragen bezüglich leihgaben.
Durch die Absagen musste ein neues umdenken geschehen und neue Hersteller eruiert werden -> problem wo gibt es andere hersteller?

2019-04-25 16:48 UTC, CryDeb commented on include/Projektmanagementplan.tex
> +In diesem Sprint wurden die erarbeiteten Konzepte noch einmal kritisch begutachtet, harmonisiert und für die Machbarkeitsstudie finalisiert. Alle Versuche Leihgaben zu erhalten scheiterten jedoch. Vo
Problem aus Sprint 03 wurde mitgenommen, als Ziel galt es dieses Problem zu lösen. Get a RFID reader as cheap as possible and it has to arrive at the end of this sprint.

2019-04-25 16:48 UTC, CryDeb commented on include/Projektmanagementplan.tex
> +In diesem Sprint wurden die erarbeiteten Konzepte noch einmal kritisch begutachtet, harmonisiert und für die Machbarkeitsstudie finalisiert. Alle Versuche Leihgaben zu erhalten scheiterten jedoch. Vo
ein Testframework zu definieren -> und für die durchführung der Test eine Applikation zu erstellen ..... (irgenwie noch sagen, dass es erstellt werden soll, damit das protokoll genauer sein kann sowie die Zeitkritischen funktionen auf die ms genau gemesen werden können, was von hand gar nicht oder nur begrenz möglich sei)

2019-04-25 16:48 UTC, CryDeb commented on include/Projektmanagementplan.tex
> +In diesem Sprint wurden die erarbeiteten Konzepte noch einmal kritisch begutachtet, harmonisiert und für die Machbarkeitsstudie finalisiert. Alle Versuche Leihgaben zu erhalten scheiterten jedoch. Vo
Kann man Motivationsverlust umschreiben ?

2019-04-26 09:52 UTC, KilnOfTheSecondFlame commented on include/Projektmanagementplan.tex
> +In diesem Sprint wurden die erarbeiteten Konzepte noch einmal kritisch begutachtet, harmonisiert und für die Machbarkeitsstudie finalisiert. Alle Versuche Leihgaben zu erhalten scheiterten jedoch. Vo
-> Habe nun Motivationsdämpfer geschrieben

2019-04-26 11:49 UTC, CryDeb approved these changes

2019-04-26 11:49 UTC, CryDeb commented on include/Projektmanagementplan.tex
> +Der Sprint war durch eine Vielzahl von Problemen geplagt. Zum einen war dies die späte Ankunft der Testgeräte auf das Ende des Sprints, zum zweiten die Verzögerung des Abschlusses des letzten Sprints
Was für masnahmen -> nimmt mich wunder

2019-04-26 11:49 UTC, CryDeb commented on include/Projektmanagementplan.tex
> +Das angetroffene Problem dieses Sprints war, dass die Spezifikation des Gerätetreibers weniger gut als erhofft war. Insbesondere muss die DLL des Händlers verwendet werden, welche nur durch eine 32bi
die dll kann nur mit einer 32-Bit Applikation aufgerufen werden (sie wird nicht gemacht)

2019-04-26 13:42 UTC, KilnOfTheSecondFlame commented on include/Projektmanagementplan.tex
> +Der Sprint war durch eine Vielzahl von Problemen geplagt. Zum einen war dies die späte Ankunft der Testgeräte auf das Ende des Sprints, zum zweiten die Verzögerung des Abschlusses des letzten Sprints
Sind im nächsten Abschnitt genauer beschrieben, passt das?

2019-04-28 18:09 UTC, merged