Feature/Methode&Abgrenzungen
HSLU-BaumannWicki/BDA_FS19-Dokumentation pull request #22
Opened 2019-05-21 16:29 UTC by KilnOfTheSecondFlame

2019-05-22 05:33 UTC, CryDeb requested changes
Past tense or presence

2019-05-22 05:33 UTC, CryDeb commented on include/Methode.tex
> +In diesem Projekt wurde explizit auf eine Implementation mit dem Lagerverwaltungssystem verzichtet, da der Fokus auf der Machbarkeitsstudie lag. Es wurde diese Implementation zwar berücksichtigt, abe
_Es wurde diese Implementation zwar berücksichtigt, aber sie stellt eine Unbekannte für das Folgeprojekt dar._ 
Was meinst du genau?
* Was wurde berücksichtigt
* Wie wurde es berücksichtigt
* Bei welcher Implementation wurde es berücksichtigt

Weiter wurde explizit die Entwicklung des **Prototypen** zur Produktionsreife als nicht Teil des Projektes verstanden. Die Referenzimplementation wurde als Validierung der Konzepte und Versuche verstanden, und nicht als **Prototyp** zur Einbindung in die Umgebung.
Wo gibt es dann ein Prototypen? -> im ersten Satz gibt es ja einen im Zweiten wird verständlich gemacht, dass es sich um keinen handelt.

2019-05-22 05:33 UTC, CryDeb commented on include/Methode.tex
> +Für dieses Projekt wurde auch die Einbindung in die Datenbank des Lagerverwaltungssystem durch eine Momentanaufnahme als Dump abstrahiert, eine dynamische Einbindung ist daher auch Teil des Folgeproj
Für dieses Projekt wurde auch die Einbindung in die Datenbank des Lagerverwaltungssystem durch eine Momentanaufnahme als Dump abstrahiert, eine dynamische Einbindung ist daher auch Teil des Folgeprojektes.

So nicht ganz korrekt. Es wird nichts abstrahiert, wir greifen gemäss Planung auf eine korrekte Datenbankinstanz zu und nicht auf eine Abstraktion. Wir greifen ja nur nicht auf das Live-System zu, da dazu etwas mehr Zeit beim Kunden vor Ort gebraucht werden würde.

2019-05-22 05:33 UTC, CryDeb commented on include/Methode.tex
> +Für dieses Projekt wurde auch die Einbindung in die Datenbank des Lagerverwaltungssystem durch eine Momentanaufnahme als Dump abstrahiert, eine dynamische Einbindung ist daher auch Teil des Folgeproj
En Idee:
Für dieses Projekt wurde der Anschluss an die aktive Datenbank des Lagerverwaltungssystem durch eine lokale Instanz, welche mit einer Momentaufnahmen der realen Datenbank gefüllt ist, ersetzt.

2019-05-23 06:41 UTC, KilnOfTheSecondFlame commented on include/Methode.tex
> +In diesem Projekt wurde explizit auf eine Implementation mit dem Lagerverwaltungssystem verzichtet, da der Fokus auf der Machbarkeitsstudie lag. Es wurde diese Implementation zwar berücksichtigt, abe
Wurde im Rahmen der Machbarkeitsstudie berücksichtig, sprich für das Folgeprojekt geplant

2019-05-26 17:02 UTC, CryDeb requested changes

2019-05-26 17:02 UTC, CryDeb commented on include/Methode.tex
> +In diesem Projekt wurde explizit auf eine Einbindung eines Prototyps mit dem Lagerverwaltungssystem verzichtet, da der Fokus auf der Machbarkeitsstudie lag. Es wurde dieser Prototyp zwar in der Planu
Es wurde dieser Prototyp zwar in der Planung des Folgeprojektes im Rahmen der Machbarkeitsstudie berücksichtigt, aber dessen genaue Form liegt im ermessen des nächsten Projektteams. 
_Denkst du wirklich man kann es im folgeprojekt noch Prototyp nennen -> soll ja produktiviert werden also eher kein prototyp._

Weiter macht der Satz so keinen sinn. **Der Prototyp wurde in der Planung des Folgeprojektes, im Rahmen der Machbarkeitsstudie, berücksichtigt. Die Form des Prototypen wurde jedoch nicht genauer erwähnt, sodass diese Spezifikation im ermessen des nächsten Projektteames liegt.**

2019-05-26 17:02 UTC, CryDeb commented on include/Methode.tex
> +In diesem Projekt wurde explizit auf eine Einbindung eines Prototyps mit dem Lagerverwaltungssystem verzichtet, da der Fokus auf der Machbarkeitsstudie lag. Es wurde dieser Prototyp zwar in der Planu
Weiter wurde explizit die Entwicklung der Referenzimplementation zur Produktionsreife als nicht Teil des Projektes verstanden. Diese wurde als Validierung der Konzepte und Versuche verstanden.
_Macht es Sinn dies zu erwähnen? -> eine Referenzimplementation wird ja nie produktiviert hingegen die Applikation des folgeprojektes schon._

Allenfals so umschreiben:
Um die Konzepte, sowie die Versuche vor Ort möglichst gut Validieren zu können, soll eine Referenzimplementation entwickelt werden, welche nicht produktiviert werden soll

2019-05-26 17:02 UTC, CryDeb commented on include/Methode.tex
> +Für dieses Projekt wurde auch die Einbindung in die Datenbank des Lagerverwaltungssystems ausgeschlossen, eine dynamische Einbindung ist daher auch Teil des Folgeprojektes. Zur Entwicklung der Refere
Schau dir die Anforderungen an, dort steht geschriben, dass wir eine Anbindung an eine Oracle Datenbank haben.
Daher würde ich diesen satz löschen.

2019-05-26 18:06 UTC, CryDeb approved these changes

2019-05-26 18:06 UTC, CryDeb commented on include/Methode.tex
> +Um die Konzepte, sowie Versuche, vor Ort zu validieren, wurde eine Referenzimplementation entwickelt, diese zu einer Produktionsreife zu bringen war explizit nicht Teil des Projektes. Die Applikation
Um die Konzepte sowie Versuche vor Ort zu validieren

2019-05-26 18:07 UTC, merged