Feature/sysspec
HSLU-BaumannWicki/BDA_FS19-Dokumentation pull request #32
Opened 2019-05-29 15:43 UTC by CryDeb

2019-05-30 06:19 UTC, KilnOfTheSecondFlame commented on BDA_FS19_Projektdokumentation.tex
> +\newglossaryentry{DLL}{name={DLL},description={Dinamic Link Library, eine dynamisch ladbare Programmbibliothek}}
_Dynamic_ Link Library

2019-05-30 06:19 UTC, KilnOfTheSecondFlame commented on include/Methode.tex
> +Um dieses Ziel zu erreichen wurden verschiedenen Anforderungen erhoben.
ermittelt / identifiziert

2019-05-30 06:19 UTC, KilnOfTheSecondFlame commented on include/Realisierung.tex
> +Durch Auslesen mehrerer ausgeliehenen Büchern und dem Abgleich mit der erhaltenen Datenbank von der Speicherbibliothek, wurde herausgefunden, dass die Blöcke null bis drei die für die Buch-ID relevan
Gut, danke dir, shame on me, dass ich das nicht sauberer geschrieben habe

2019-05-31 07:36 UTC, KilnOfTheSecondFlame requested changes

2019-05-31 07:36 UTC, KilnOfTheSecondFlame commented on include/Realisierung.tex
> +Gut lesbarer Code ist verständlicher als veralteter, nicht akkurater Kommentar. Diesem Zustand haben wir entgegengesetzt, indem wir auf JavaDoc, sowie nicht notwendige Kommentare verzichtet haben. Di
Gut lesbarer Code ist verständlicher als __ein__ veralteter, nicht akkurater Kommentar.

2019-05-31 07:36 UTC, KilnOfTheSecondFlame commented on include/Realisierung.tex
> +Gut lesbarer Code ist verständlicher als veralteter, nicht akkurater Kommentar. Diesem Zustand haben wir entgegengesetzt, indem wir auf JavaDoc, sowie nicht notwendige Kommentare verzichtet haben. Di
Dieser Entscheid hatte zur Folge, dass eine sprechende Namensgebung für alle zu benennende Elemente im Code verwendet wurden _musste_.

Ich glaube du wolltest das so sagen nicht? Sonst darfst du das auch weglassen

2019-05-31 07:36 UTC, KilnOfTheSecondFlame commented on include/Realisierung.tex
> +Um möglichst effizient und unabhängig voneinander zu programmieren, sowie zu dokumentieren, wurde mit dem Feature Branch Workflow gearbeitet. Dies bedeutet, dass für jedes Feature einen Branch erstel
Weiter wurde eine Regelung eingeführt, wobei ein Branch nicht vom Ersteller ~in den~ __mit dem__ Master Branch zusammengeführt werden darf.

oder

Weiter wurde eine Regelung eingeführt, wobei ein Branch nicht vom Ersteller in den Master Branch ~zusammengeführt~ _eingepflegt / eingefügt_ werden darf.

2019-05-31 07:36 UTC, KilnOfTheSecondFlame commented on include/Realisierung.tex
> +Um möglichst effizient und unabhängig voneinander zu programmieren, sowie zu dokumentieren, wurde mit dem Feature Branch Workflow gearbeitet. Dies bedeutet, dass für jedes Feature einen Branch erstel
[...] Review der Dokumentation, respektive des Codes durchführen muss.

2019-06-01 09:32 UTC, CryDeb commented on include/Realisierung.tex
> +Gut lesbarer Code ist verständlicher als veralteter, nicht akkurater Kommentar. Diesem Zustand haben wir entgegengesetzt, indem wir auf JavaDoc, sowie nicht notwendige Kommentare verzichtet haben. Di
nein ist schon korrekt wie es geschrieben ist

2019-06-01 20:24 UTC, KilnOfTheSecondFlame approved these changes

2019-06-01 20:26 UTC, merged